### ISSUE TITLE
bug of update function in tutorial

### ISSUE THREAD

**Issue by skasberger** [activepapers/activepapers-python#10]
i tried to do the [tutorial](http://www.activepapers.org/python-edition/tutorial.html) and got this bug.
- ubuntu 13.10
- python 2.7.5+
- aptool 0.1.3
```
aptool update -v
Dataset /data/coordinate_trajectories/rotation_laboratory_frame_4 is stale or dummy, running /code/trajectory_processing
Traceback (most recent call last):
  File "/usr/local/bin/aptool", line 251, in <module>
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/activepapers/cli.py", line 424, in update
    calclet, item_name = _find_calclet_for_dummy_or_stale_item(paper_name)
  File "/usr/local/lib/python2.7/dist-packages/activepapers/cli.py", line 403, in _find_calclet_for_dummy_or_stale_item
    next(deps) # the first set has no dependencies
  File "/usr/local/lib/python2.7/dist-packages/activepapers/storage.py", line 477, in dependency_hierarchy
    frozenset(dep.name for dep in self.iter_dependencies(item)))
  File "/usr/local/lib/python2.7/dist-packages/activepapers/storage.py", line 477, in <genexpr>
    frozenset(dep.name for dep in self.iter_dependencies(item)))
  File "/usr/local/lib/python2.7/dist-packages/activepapers/storage.py", line 412, in iter_dependencies
    yield self.file[dep]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 127, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._shared.lapl)
  File "h5o.pyx", line 178, in h5py.h5o.open (h5py/h5o.c:2751)
KeyError: "unable to open object (Symbol table: Can't open object)"
```

**Comment by khinsen** [comment]
See my comment on #11.
