### ISSUE TITLE
bug after checkin in tutorial

### ISSUE THREAD

**Issue by skasberger** [activepapers/activepapers-python#11]
i tried to do the [tutorial](http://www.activepapers.org/python-edition/tutorial.html) and got this bug after checkin of my change in plots.py.
- ubuntu 13.10
- python 2.7.5+
- aptool 0.1.3
```
aptool ls -l           
2013-06-07/09:13:05  calclet    code/correlation_functions
2013-06-07/09:19:48  calclet    code/diffusion_tensor
2013-06-07/10:02:29  calclet    code/identify_trajectories
2015-01-03/16:30:09  calclet    code/plots
2013-06-04/15:42:02  module     code/python-packages/fitting
2013-05-02/15:11:53  module     code/python-packages/molecular_structure
2013-06-14/15:46:18  reference  code/python-packages/mosaic
2013-05-23/11:42:31  module     code/python-packages/quaternion
2013-05-27/04:13:09  module     code/python-packages/time_series
2013-05-02/15:12:07  module     code/python-packages/units
2013-06-07/09:57:45  calclet    code/thermal_averages
2013-06-14/15:46:01  calclet    code/trajectory_processing
2013-06-14/15:55:00  data       data/correlation_function_integration_limit
2013-06-14/15:55:00  data       data/correlation_function_plot_range
2013-06-14/15:47:50  data      Traceback (most recent call last):
  File "/usr/local/bin/aptool", line 251, in <module>
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/activepapers/cli.py", line 231, in ls
    sys.stdout.write('*' if paper.is_stale(item) else ' ')
  File "/usr/local/lib/python2.7/dist-packages/activepapers/storage.py", line 416, in is_stale
    for dep in self.iter_dependencies(item):
  File "/usr/local/lib/python2.7/dist-packages/activepapers/storage.py", line 412, in iter_dependencies
    yield self.file[dep]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 127, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._shared.lapl)
  File "h5o.pyx", line 178, in h5py.h5o.open (h5py/h5o.c:2751)
KeyError: "unable to open object (Symbol table: Can't open object)"

```

**Comment by khinsen** [comment]
Could you please check if this problem still occurs with more recent software versions? I have seen similar problems with specific versions of HDF5 in the past. I haven't been able to reproduce this issue on any of the platforms I use, so I suspect this is strongly dependent on specific versions of some dependency.
